spring:
  application:
    name: WeiXinNotice
  redis:
    host: 119.3.100.252
    password: wanqiu
    port: 6379
    database: 10
  datasource:
    username: root
    password: jiang991011
    url: jdbc:mysql://119.3.100.252:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8090
mybatis-plus:
  # xml地址
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.wq.notice.entity   #自己的实体类地址
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  mapper-locations: classpath:mapper/*.xml

# mybatis  日志sql信息输出
logging:
  level:
    com.suncaper.springboot.demo.crud.mapper: debug
